//! Offline-генератор Rust registry из закреплённой TDLib-схемы.

#![forbid(unsafe_code)]

use serde_json::Value;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use telegram_core::schema::{Definition, DefinitionKind, Parameter, Schema, TypeRef};

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let generated_path = root.join("crates/telegram-core/src/registry/generated.rs");
    let generated = generate(&root)?;

    if env::args().nth(1).as_deref() == Some("--check") {
        if fs::read_to_string(&generated_path)? != generated {
            return Err(
                "generated TDLib registry is stale; run `cargo run -p tdlib-registry-gen`".into(),
            );
        }
        println!("generated TDLib registry: current");
    } else {
        fs::write(&generated_path, generated)?;
        println!("generated TDLib registry: updated");
    }
    Ok(())
}

fn generate(root: &Path) -> Result<String, Box<dyn Error>> {
    let source = fs::read_to_string(root.join("vendor/tdlib/td_api.tl"))?;
    let manifest: Value = serde_json::from_str(&fs::read_to_string(
        root.join("vendor/tdlib/manifest.json"),
    )?)?;
    let schema = Schema::parse(&source)?;
    let upstream = &manifest["upstream"];
    let schema_manifest = &manifest["schema"];

    let mut output = String::from(
        "// @generated by tdlib-registry-gen; do not edit.\n\
         use super::{FieldDescriptor, SchemaDescriptor, SymbolDescriptor, SymbolKind, TypeDescriptor};\n\n",
    );
    writeln!(
        output,
        "pub const SCHEMA: SchemaDescriptor = SchemaDescriptor {{ version: {:?}, commit: {:?}, sha256: {:?} }};",
        text(upstream, "version")?,
        text(upstream, "commit")?,
        text(schema_manifest, "sha256")?,
    )?;

    let mut builtins = schema
        .definitions()
        .iter()
        .filter(|definition| definition.kind() == DefinitionKind::Builtin)
        .collect::<Vec<_>>();
    let mut constructors = schema
        .definitions()
        .iter()
        .filter(|definition| definition.kind() == DefinitionKind::Constructor)
        .collect::<Vec<_>>();
    let mut methods = schema.methods().iter().collect::<Vec<_>>();
    builtins.sort_unstable_by_key(|definition| definition.name());
    constructors.sort_unstable_by_key(|definition| definition.name());
    methods.sort_unstable_by_key(|definition| definition.name());

    write_symbols(&mut output, "BUILTINS", DefinitionKind::Builtin, &builtins)?;
    write_symbols(
        &mut output,
        "CONSTRUCTORS",
        DefinitionKind::Constructor,
        &constructors,
    )?;
    write_symbols(&mut output, "METHODS", DefinitionKind::Method, &methods)?;

    let inventory = schema.inventory();
    write_names(&mut output, "TYPES", inventory.type_names())?;
    write_names(&mut output, "UPDATES", inventory.update_names())?;
    write_names(
        &mut output,
        "AUTHORIZATION_STATES",
        inventory.authorization_state_names(),
    )?;
    Ok(output)
}

fn text<'a>(value: &'a Value, field: &str) -> Result<&'a str, Box<dyn Error>> {
    value[field]
        .as_str()
        .ok_or_else(|| format!("manifest field `{field}` must be a string").into())
}

fn write_symbols(
    output: &mut String,
    name: &str,
    kind: DefinitionKind,
    definitions: &[&Definition],
) -> std::fmt::Result {
    writeln!(output, "\npub static {name}: &[SymbolDescriptor] = &[")?;
    for definition in definitions {
        write!(
            output,
            "    SymbolDescriptor {{ kind: SymbolKind::{kind:?}, name: {:?}, result: ",
            definition.name(),
        )?;
        write_type(output, definition.result())?;
        write!(
            output,
            ", signature: {:?}, documentation: {:?}, fields: &[",
            definition.canonical_signature(),
            definition.documentation().raw_lines().join("\n"),
        )?;
        for parameter in definition.parameters() {
            if let Parameter::Field { name, ty } = parameter {
                write!(output, "FieldDescriptor {{ name: {name:?}, ty: ")?;
                write_type(output, ty)?;
                output.push_str(" },");
            }
        }
        output.push_str("] },\n");
    }
    output.push_str("];\n");
    Ok(())
}

fn write_type(output: &mut String, ty: &TypeRef) -> std::fmt::Result {
    write!(
        output,
        "TypeDescriptor {{ name: {:?}, arguments: &[",
        ty.name()
    )?;
    for argument in ty.arguments() {
        write_type(output, argument)?;
        output.push(',');
    }
    output.push_str("] }");
    Ok(())
}

fn write_names(output: &mut String, name: &str, values: &[&str]) -> std::fmt::Result {
    writeln!(output, "\npub static {name}: &[&str] = &[")?;
    for value in values {
        writeln!(output, "    {value:?},")?;
    }
    output.push_str("];\n");
    Ok(())
}
