//! Offline-генератор Rust registry из закреплённой TDLib-схемы.

#![forbid(unsafe_code)]

use serde::Deserialize;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use telegram_core::schema::{Definition, DefinitionKind, Parameter, Schema, TypeRef};

const COVERAGE_BEGIN: &str = "<!-- BEGIN GENERATED TDLIB COVERAGE -->";
const COVERAGE_END: &str = "<!-- END GENERATED TDLIB COVERAGE -->";

struct GeneratedArtifacts {
    registry: String,
    coverage: String,
}

struct CoverageCounts {
    schema_methods: usize,
    registry_methods: usize,
    schema_constructors: usize,
    registry_constructors: usize,
    types: usize,
    schema_updates: usize,
    registry_updates: usize,
    schema_authorization_states: usize,
    registry_authorization_states: usize,
    reviewed: usize,
}

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let generated_path = root.join("crates/telegram-core/src/registry/generated.rs");
    let coverage_path = root.join("docs/tdlib-api-coverage.md");
    let generated = generate(&root)?;

    if env::args().nth(1).as_deref() == Some("--check") {
        if fs::read_to_string(&generated_path)? != generated.registry
            || fs::read_to_string(&coverage_path)? != generated.coverage
        {
            return Err(
                "generated TDLib registry/report is stale; run `cargo run -p tdlib-registry-gen`"
                    .into(),
            );
        }
        println!("generated TDLib registry/report: current");
    } else {
        fs::write(&generated_path, generated.registry)?;
        fs::write(&coverage_path, generated.coverage)?;
        println!("generated TDLib registry/report: updated");
    }
    Ok(())
}

fn generate(root: &Path) -> Result<GeneratedArtifacts, Box<dyn Error>> {
    let source = fs::read_to_string(root.join("vendor/tdlib/td_api.tl"))?;
    let manifest: Value = serde_json::from_str(&fs::read_to_string(
        root.join("vendor/tdlib/manifest.json"),
    )?)?;
    let schema = Schema::parse(&source)?;
    let capability_table: CapabilityTable = serde_json::from_str(&fs::read_to_string(
        root.join("tools/tdlib-registry-gen/capabilities.json"),
    )?)?;
    let upstream = &manifest["upstream"];
    let schema_manifest = &manifest["schema"];

    let mut output = String::from(
        "// @generated by tdlib-registry-gen; do not edit.\n\
         use super::{AccountKind, CapabilityDescriptor, CapabilityDisposition, FieldDescriptor, RetryClass, RiskClass, SchemaDescriptor, SymbolDescriptor, SymbolKind, TypeDescriptor};\n\n",
    );
    writeln!(
        output,
        "pub const SCHEMA: SchemaDescriptor = SchemaDescriptor {{ version: {:?}, commit: {:?}, sha256: {:?} }};",
        text(upstream, "version")?,
        text(upstream, "commit")?,
        text(schema_manifest, "sha256")?,
    )?;

    let mut builtins = schema
        .definitions()
        .iter()
        .filter(|definition| definition.kind() == DefinitionKind::Builtin)
        .collect::<Vec<_>>();
    let mut constructors = schema
        .definitions()
        .iter()
        .filter(|definition| definition.kind() == DefinitionKind::Constructor)
        .collect::<Vec<_>>();
    let mut methods = schema.methods().iter().collect::<Vec<_>>();
    builtins.sort_unstable_by_key(|definition| definition.name());
    constructors.sort_unstable_by_key(|definition| definition.name());
    methods.sort_unstable_by_key(|definition| definition.name());
    let capabilities = validate_capabilities(capability_table, &methods)?;

    write_symbols(&mut output, "BUILTINS", DefinitionKind::Builtin, &builtins)?;
    write_symbols(
        &mut output,
        "CONSTRUCTORS",
        DefinitionKind::Constructor,
        &constructors,
    )?;
    write_symbols(&mut output, "METHODS", DefinitionKind::Method, &methods)?;
    write_capabilities(&mut output, &methods, &capabilities)?;

    let inventory = schema.inventory();
    write_names(&mut output, "TYPES", inventory.type_names())?;
    write_names(&mut output, "UPDATES", inventory.update_names())?;
    write_names(
        &mut output,
        "AUTHORIZATION_STATES",
        inventory.authorization_state_names(),
    )?;
    let coverage_block = coverage_block(
        text(upstream, "version")?,
        text(upstream, "commit")?,
        text(schema_manifest, "sha256")?,
        CoverageCounts {
            schema_methods: number(schema_manifest, "functions")?,
            registry_methods: methods.len(),
            schema_constructors: number(schema_manifest, "definitions")?
                .checked_sub(builtins.len())
                .ok_or("manifest definitions are fewer than schema builtins")?,
            registry_constructors: constructors.len(),
            types: inventory.type_names().len(),
            schema_updates: number(schema_manifest, "updates")?,
            registry_updates: inventory.update_names().len(),
            schema_authorization_states: number(schema_manifest, "authorization_states")?,
            registry_authorization_states: inventory.authorization_state_names().len(),
            reviewed: capabilities.len(),
        },
    )?;
    let coverage_source = fs::read_to_string(root.join("docs/tdlib-api-coverage.md"))?;
    Ok(GeneratedArtifacts {
        registry: output,
        coverage: replace_generated_coverage(&coverage_source, &coverage_block)?,
    })
}

fn coverage_block(
    version: &str,
    commit: &str,
    schema_sha256: &str,
    counts: CoverageCounts,
) -> Result<String, std::fmt::Error> {
    let CoverageCounts {
        schema_methods,
        registry_methods,
        schema_constructors,
        registry_constructors,
        types,
        schema_updates,
        registry_updates,
        schema_authorization_states,
        registry_authorization_states,
        reviewed,
    } = counts;
    let mut output = String::new();
    writeln!(
        output,
        "TDLib `{version}`, commit `{commit}`, schema `{schema_sha256}`."
    )?;
    writeln!(output)?;
    writeln!(output, "| Contract metric | Count | Status |")?;
    writeln!(output, "|---|---:|---|")?;
    writeln!(
        output,
        "| `schema_functions` | {schema_methods} | pinned manifest |"
    )?;
    writeln!(
        output,
        "| `registry_methods` | {registry_methods} | generated |"
    )?;
    writeln!(
        output,
        "| `core_raw_methods` | {registry_methods} | one validated `td_call` |"
    )?;
    writeln!(
        output,
        "| capability descriptors | {registry_methods} | reviewed or `DefaultDeny` |"
    )?;
    writeln!(
        output,
        "| reviewed methods | {reviewed} | explicit data rows |"
    )?;
    writeln!(
        output,
        "| default-deny methods | {} | valid unreviewed state |",
        registry_methods - reviewed
    )?;
    writeln!(
        output,
        "| schema object constructors | {schema_constructors} | manifest definitions minus parsed builtins |"
    )?;
    writeln!(
        output,
        "| registry/codec constructors | {registry_constructors} | generated/lossless |"
    )?;
    writeln!(output, "| distinct result types | {types} | generated |")?;
    writeln!(
        output,
        "| schema updates | {schema_updates} | pinned manifest |"
    )?;
    writeln!(
        output,
        "| registry/lossless updates | {registry_updates} | ordered reducer + raw fallback |"
    )?;
    writeln!(
        output,
        "| schema authorization states | {schema_authorization_states} | pinned manifest |"
    )?;
    writeln!(
        output,
        "| registry/handled auth states | {registry_authorization_states} | exhaustive auth machine |"
    )?;
    writeln!(output)?;
    writeln!(output, "Core equality: `schema_functions({schema_methods}) == registry_methods({registry_methods}) == core_raw_methods({registry_methods})`. CLI/MCP parity остаётся незакрытой до соответствующих phases; workflow/live levels считаются отдельно.")?;
    Ok(output)
}

fn replace_generated_coverage(source: &str, block: &str) -> Result<String, Box<dyn Error>> {
    if source.matches(COVERAGE_BEGIN).count() != 1 || source.matches(COVERAGE_END).count() != 1 {
        return Err("coverage report markers must be unique".into());
    }
    let begin = source
        .find(COVERAGE_BEGIN)
        .ok_or("coverage report is missing begin marker")?;
    let content_start = begin + COVERAGE_BEGIN.len();
    let relative_end = source[content_start..]
        .find(COVERAGE_END)
        .ok_or("coverage report is missing end marker")?;
    let end = content_start + relative_end;
    Ok(format!(
        "{}\n{}{}{}",
        &source[..content_start],
        block,
        COVERAGE_END,
        &source[end + COVERAGE_END.len()..]
    ))
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CapabilityTable {
    reviewed: Vec<CapabilityRow>,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CapabilityRow {
    method: String,
    risk: String,
    accounts: Vec<String>,
    runtime_requirements: String,
    retry: String,
}

fn validate_capabilities(
    table: CapabilityTable,
    methods: &[&Definition],
) -> Result<BTreeMap<String, CapabilityRow>, Box<dyn Error>> {
    let known = methods
        .iter()
        .map(|method| method.name())
        .collect::<BTreeSet<_>>();
    let mut reviewed = BTreeMap::new();
    for row in table.reviewed {
        if !known.contains(row.method.as_str()) {
            return Err(
                format!("capability row references unknown method `{}`", row.method).into(),
            );
        }
        if risk_variant(&row.risk).is_none() || retry_variant(&row.retry).is_none() {
            return Err(format!("capability row for `{}` has an unknown class", row.method).into());
        }
        let accounts = row
            .accounts
            .iter()
            .map(|account| account_variant(account))
            .collect::<Option<BTreeSet<_>>>()
            .ok_or_else(|| format!("capability row for `{}` has an unknown account", row.method))?;
        if accounts.is_empty() || accounts.len() != row.accounts.len() {
            return Err(format!("capability row for `{}` has invalid accounts", row.method).into());
        }
        if row.runtime_requirements.trim().is_empty() {
            return Err(
                format!("capability row for `{}` has empty requirements", row.method).into(),
            );
        }
        let method = row.method.clone();
        if reviewed.insert(method.clone(), row).is_some() {
            return Err(format!("duplicate capability row for `{method}`").into());
        }
    }
    Ok(reviewed)
}

fn risk_variant(value: &str) -> Option<&'static str> {
    match value {
        "read" => Some("Read"),
        "presence" => Some("Presence"),
        "send" => Some("Send"),
        "reversible_mutation" => Some("ReversibleMutation"),
        "admin" => Some("Admin"),
        "destructive" => Some("Destructive"),
        "financial" => Some("Financial"),
        "auth_security" => Some("AuthSecurity"),
        _ => None,
    }
}

fn retry_variant(value: &str) -> Option<&'static str> {
    match value {
        "safe_read" => Some("SafeRead"),
        "convergent" => Some("Convergent"),
        "reconcile" => Some("Reconcile"),
        "never" => Some("Never"),
        _ => None,
    }
}

fn account_variant(value: &str) -> Option<&'static str> {
    match value {
        "regular_user" => Some("RegularUser"),
        "bot" => Some("Bot"),
        _ => None,
    }
}

fn text<'a>(value: &'a Value, field: &str) -> Result<&'a str, Box<dyn Error>> {
    value[field]
        .as_str()
        .ok_or_else(|| format!("manifest field `{field}` must be a string").into())
}

fn number(value: &Value, field: &str) -> Result<usize, Box<dyn Error>> {
    value[field]
        .as_u64()
        .and_then(|value| usize::try_from(value).ok())
        .ok_or_else(|| format!("manifest field `{field}` must be an unsigned integer").into())
}

fn write_symbols(
    output: &mut String,
    name: &str,
    kind: DefinitionKind,
    definitions: &[&Definition],
) -> std::fmt::Result {
    writeln!(output, "\npub static {name}: &[SymbolDescriptor] = &[")?;
    for definition in definitions {
        write!(
            output,
            "    SymbolDescriptor {{ kind: SymbolKind::{kind:?}, name: {:?}, result: ",
            definition.name(),
        )?;
        write_type(output, definition.result())?;
        write!(
            output,
            ", signature: {:?}, documentation: {:?}, fields: &[",
            definition.canonical_signature(),
            definition.documentation().raw_lines().join("\n"),
        )?;
        for parameter in definition.parameters() {
            if let Parameter::Field { name, ty } = parameter {
                write!(output, "FieldDescriptor {{ name: {name:?}, ty: ")?;
                write_type(output, ty)?;
                output.push_str(" },");
            }
        }
        output.push_str("] },\n");
    }
    output.push_str("];\n");
    Ok(())
}

fn write_type(output: &mut String, ty: &TypeRef) -> std::fmt::Result {
    write!(
        output,
        "TypeDescriptor {{ name: {:?}, arguments: &[",
        ty.name()
    )?;
    for argument in ty.arguments() {
        write_type(output, argument)?;
        output.push(',');
    }
    output.push_str("] }");
    Ok(())
}

fn write_names(output: &mut String, name: &str, values: &[&str]) -> std::fmt::Result {
    writeln!(output, "\npub static {name}: &[&str] = &[")?;
    for value in values {
        writeln!(output, "    {value:?},")?;
    }
    output.push_str("];\n");
    Ok(())
}

fn write_capabilities(
    output: &mut String,
    methods: &[&Definition],
    reviewed: &BTreeMap<String, CapabilityRow>,
) -> Result<(), Box<dyn Error>> {
    output.push_str("\npub static CAPABILITIES: &[CapabilityDescriptor] = &[\n");
    for method in methods {
        write!(
            output,
            "    CapabilityDescriptor {{ method: {:?}, disposition: ",
            method.name()
        )?;
        if let Some(row) = reviewed.get(method.name()) {
            write!(
                output,
                "CapabilityDisposition::Reviewed {{ risk: RiskClass::{}, accounts: &[",
                risk_variant(&row.risk).expect("validated risk class")
            )?;
            for account in &row.accounts {
                write!(
                    output,
                    "AccountKind::{},",
                    account_variant(account).expect("validated account")
                )?;
            }
            write!(
                output,
                "], runtime_requirements: {:?}, retry: RetryClass::{} }}",
                row.runtime_requirements,
                retry_variant(&row.retry).expect("validated retry class")
            )?;
        } else {
            output.push_str("CapabilityDisposition::DefaultDeny");
        }
        output.push_str(" },\n");
    }
    output.push_str("];\n");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn method_schema() -> Schema {
        Schema::parse("ok = Ok;\n---functions---\ngetOk = Ok;").unwrap()
    }

    fn row(method: &str) -> CapabilityRow {
        CapabilityRow {
            method: method.to_owned(),
            risk: "read".to_owned(),
            accounts: vec!["regular_user".to_owned()],
            runtime_requirements: "Ready".to_owned(),
            retry: "safe_read".to_owned(),
        }
    }

    #[test]
    fn capability_data_rejects_unknown_and_duplicate_methods() {
        let schema = method_schema();
        let methods = schema.methods().iter().collect::<Vec<_>>();
        assert!(validate_capabilities(
            CapabilityTable {
                reviewed: vec![row("unknown")]
            },
            &methods
        )
        .is_err());
        assert!(validate_capabilities(
            CapabilityTable {
                reviewed: vec![row("getOk"), row("getOk")]
            },
            &methods
        )
        .is_err());
    }

    #[test]
    fn coverage_markers_replace_only_generated_content() {
        let source = format!("before\n{COVERAGE_BEGIN}\nold\n{COVERAGE_END}\nafter\n");
        assert_eq!(
            replace_generated_coverage(&source, "new\n").unwrap(),
            format!("before\n{COVERAGE_BEGIN}\nnew\n{COVERAGE_END}\nafter\n")
        );
        assert!(replace_generated_coverage("no markers", "new").is_err());
    }
}
