use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::mpsc;
use std::thread;

use serde_json::json;
use sha2::{Digest, Sha256};

use super::{
    AppErrorKind, Command, OUTPUT_PATH, Outcome, TEMP_SUFFIX, atomic_publish, parse_command, run,
};

const SCHEMA: &str = "\
string ? = String;\n\
int53 = Int53;\n\
ok = Ok;\n\
user = User;\n\
chat = Chat;\n\
---functions---\n\
getUser id:int53 = User;\n\
setUserName name:string = Ok;\n\
getChat id:int53 = Chat;\n\
deleteChat id:int53 = Ok;\n";

const USER_SET_SHA256: &str = "4fcc9bd48d78cd718fa78cb8c9eee7d5d12ab1e330f5abeb49e4ac2f612d19b5";
const CHAT_SET_SHA256: &str = "0ca418747e93361fab38c2c4f0e1019a393c90ea60a30c4ce1122ace44b3fbed";

#[test]
fn check_is_read_only_and_detects_exact_output_drift() {
    let repo = TestRepo::new();
    repo.write_inputs();
    let output = repo.root.join(OUTPUT_PATH);
    let temp = temp_path(&output);

    let error = run(&repo.root, Command::Check).expect_err("missing generated output");
    assert_eq!(error.kind(), AppErrorKind::OutOfDate);
    assert!(!output.exists());
    assert!(!temp.exists());

    assert_eq!(
        run(&repo.root, Command::Generate).expect("initial publication"),
        Outcome::Updated
    );
    assert_eq!(
        run(&repo.root, Command::Check).expect("exact generated bytes"),
        Outcome::Current
    );
    assert!(!temp.exists());

    let canonical = fs::read(&output).expect("generated output");
    let mut mutated = canonical.clone();
    let middle = mutated.len() / 2;
    mutated[middle] ^= 1;
    fs::write(&output, &mutated).expect("one-byte mutation");
    let error = run(&repo.root, Command::Check).expect_err("one-byte mutation");
    assert_eq!(error.kind(), AppErrorKind::OutOfDate);
    assert_eq!(fs::read(&output).expect("unchanged mutation"), mutated);
    assert!(!temp.exists());

    let mut trailing = canonical;
    trailing.push(b'\n');
    fs::write(&output, &trailing).expect("trailing mutation");
    let error = run(&repo.root, Command::Check).expect_err("trailing byte");
    assert_eq!(error.kind(), AppErrorKind::OutOfDate);
    assert_eq!(
        fs::read(&output).expect("unchanged trailing bytes"),
        trailing
    );
    assert!(!temp.exists());
}

#[test]
fn generate_is_noop_when_current_and_serializes_writers_with_one_temp() {
    let repo = TestRepo::new();
    repo.write_inputs();
    assert_eq!(
        run(&repo.root, Command::Generate).expect("initial publication"),
        Outcome::Updated
    );

    let output = repo.root.join(OUTPUT_PATH);
    let canonical = fs::read(&output).expect("generated output");
    let mut permissions = fs::metadata(&output).expect("metadata").permissions();
    permissions.set_readonly(true);
    fs::set_permissions(&output, permissions).expect("readonly output");
    assert_eq!(
        run(&repo.root, Command::Generate).expect("readonly no-op"),
        Outcome::Unchanged
    );
    assert_eq!(fs::read(&output).expect("same output"), canonical);

    let mut stale = canonical.clone();
    stale[0] ^= 1;
    fs::remove_file(&output).expect("replace readonly output");
    fs::write(&output, &stale).expect("stale output");

    let temp = temp_path(&output);
    fs::write(&temp, b"writer owns the fixed temp").expect("writer sentinel");
    let error = run(&repo.root, Command::Generate).expect_err("concurrent writer");
    assert_eq!(error.kind(), AppErrorKind::ConcurrentWriter);
    assert_eq!(
        fs::read(&temp).expect("sentinel remains"),
        b"writer owns the fixed temp"
    );
    assert_eq!(fs::read(&output).expect("output remains"), stale);
}

#[test]
fn writer_lease_precedes_input_snapshot_and_prevents_stale_publication() {
    let repo = TestRepo::new();
    repo.write_inputs();
    assert_eq!(
        run(&repo.root, Command::Generate).expect("old publication"),
        Outcome::Updated
    );
    let output = repo.root.join(OUTPUT_PATH);
    let old_output = fs::read(&output).expect("old output");
    fs::remove_file(&output).expect("force a new publication");

    let (lease_acquired_tx, lease_acquired_rx) = mpsc::sync_channel(0);
    let (resume_tx, resume_rx) = mpsc::sync_channel(0);
    let writer_root = repo.root.clone();
    let writer = thread::spawn(move || {
        super::run_generate_with_hook(&writer_root, || {
            lease_acquired_tx.send(()).expect("signal acquired lease");
            resume_rx.recv().expect("resume writer");
        })
    });

    lease_acquired_rx.recv().expect("writer acquired lease");
    assert!(temp_path(&output).is_file());
    repo.change_policy_rationale();
    let concurrent = run(&repo.root, Command::Generate).expect_err("one writer at a time");
    resume_tx.send(()).expect("release writer");
    let outcome = writer.join().expect("writer thread").expect("publication");

    assert_eq!(concurrent.kind(), AppErrorKind::ConcurrentWriter);
    assert_eq!(outcome, Outcome::Updated);
    assert_ne!(fs::read(&output).expect("new output"), old_output);
    assert_eq!(
        run(&repo.root, Command::Check).expect("new policy output"),
        Outcome::Current
    );
    assert!(!temp_path(&output).exists());
}

#[test]
fn atomic_publication_removes_its_temp_after_publish_failure() {
    let repo = TestRepo::new();
    let output = repo.root.join("generated/target");
    fs::create_dir_all(&output).expect("directory blocks rename");
    let temp = temp_path(&output);

    let error = atomic_publish(&output, b"bounded payload").expect_err("rename must fail");
    assert_eq!(error.kind(), AppErrorKind::Io);
    assert!(output.is_dir());
    assert!(!temp.exists());
}

#[cfg(unix)]
#[test]
fn fixed_paths_reject_symlink_inputs_outputs_and_output_directory() {
    use std::os::unix::fs::symlink;

    let input_repo = TestRepo::new();
    input_repo.write_inputs();
    let policy = input_repo.root.join("policy/tdlib-feature-owners.json");
    let external_policy = input_repo.root.join("external-policy.json");
    fs::rename(&policy, &external_policy).expect("move policy");
    symlink(&external_policy, &policy).expect("symlink policy");
    let error = run(&input_repo.root, Command::Check).expect_err("symlink input");
    assert_eq!(error.kind(), AppErrorKind::Io);

    let output_repo = TestRepo::new();
    output_repo.write_inputs();
    run(&output_repo.root, Command::Generate).expect("generated output");
    let output = output_repo.root.join(OUTPUT_PATH);
    let external_output = output_repo.root.join("external-output.json");
    fs::rename(&output, &external_output).expect("move output");
    symlink(&external_output, &output).expect("symlink output");
    let error = run(&output_repo.root, Command::Check).expect_err("symlink output");
    assert_eq!(error.kind(), AppErrorKind::Io);

    let directory_repo = TestRepo::new();
    directory_repo.write_inputs();
    let generated = directory_repo.root.join("generated");
    fs::remove_dir(&generated).expect("remove generated directory");
    let external_generated = directory_repo.root.join("external-generated");
    fs::create_dir(&external_generated).expect("external generated directory");
    symlink(&external_generated, &generated).expect("symlink generated directory");
    let error = run(&directory_repo.root, Command::Generate).expect_err("symlink output dir");
    assert_eq!(error.kind(), AppErrorKind::Io);
    assert!(
        external_generated
            .read_dir()
            .expect("external directory")
            .next()
            .is_none()
    );
}

#[cfg(unix)]
#[test]
fn publication_neither_renames_nor_deletes_a_replaced_temp_inode() {
    let repo = TestRepo::new();
    let output = repo.root.join("generated/target");
    let mut publication = super::Publication::acquire(&output).expect("publication lease");
    let temp = temp_path(&output);
    fs::remove_file(&temp).expect("unlink owned temp");
    fs::write(&temp, b"foreign successor").expect("replace temp inode");

    let error = publication
        .publish(b"owned payload")
        .expect_err("temp identity changed");
    drop(publication);

    assert_eq!(error.kind(), AppErrorKind::Io);
    assert!(!output.exists());
    assert_eq!(
        fs::read(&temp).expect("foreign temp remains"),
        b"foreign successor"
    );
}

#[test]
fn cli_accepts_exactly_one_known_command() {
    assert_eq!(parse_command(&["check".into()]).unwrap(), Command::Check);
    assert_eq!(
        parse_command(&["generate".into()]).unwrap(),
        Command::Generate
    );
    for args in [
        vec![],
        vec!["unknown".into()],
        vec!["check".into(), "x".into()],
    ] {
        assert_eq!(
            parse_command(&args).expect_err("usage error").kind(),
            AppErrorKind::Usage
        );
    }
}

struct TestRepo {
    root: PathBuf,
}

impl TestRepo {
    fn new() -> Self {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let unique = NEXT.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "tdlib-registry-gen-test-{}-{unique}",
            std::process::id()
        ));
        if root.exists() {
            fs::remove_dir_all(&root).expect("remove stale test root");
        }
        fs::create_dir_all(root.join("vendor/tdlib")).expect("vendor directory");
        fs::create_dir_all(root.join("policy")).expect("policy directory");
        fs::create_dir_all(root.join("generated")).expect("generated directory");
        Self { root }
    }

    fn write_inputs(&self) {
        fs::write(self.root.join("vendor/tdlib/td_api.tl"), SCHEMA).expect("schema");
        fs::write(
            self.root.join("vendor/tdlib/manifest.json"),
            serde_json::to_vec(&json!({
                "format_version": 1,
                "upstream": {
                    "repository": "https://example.invalid/tdlib",
                    "commit": "0123456789abcdef0123456789abcdef01234567",
                    "version": "test"
                },
                "schema": {
                    "sha256": sha256_hex(SCHEMA.as_bytes()),
                    "definitions": 5,
                    "functions": 4,
                    "updates": 0,
                    "authorization_states": 0
                }
            }))
            .expect("manifest JSON"),
        )
        .expect("manifest");
        fs::write(
            self.root.join("policy/tdlib-feature-owners.json"),
            serde_json::to_vec(&json!({
                "format_version": 1,
                "schema_sha256": sha256_hex(SCHEMA.as_bytes()),
                "rules": [
                    feature_rule(
                        "F007",
                        json!([
                            { "kind": "exact", "value": "setUserName" },
                            { "kind": "contains", "value": "User" }
                        ]),
                        2,
                        USER_SET_SHA256,
                        "getUser",
                        "getChat"
                    ),
                    feature_rule(
                        "F008",
                        json!([{ "kind": "contains", "value": "Chat" }]),
                        2,
                        CHAT_SET_SHA256,
                        "getChat",
                        "getUser"
                    )
                ],
                "overrides": []
            }))
            .expect("policy JSON"),
        )
        .expect("policy");
    }

    fn change_policy_rationale(&self) {
        let path = self.root.join("policy/tdlib-feature-owners.json");
        let mut policy: serde_json::Value =
            serde_json::from_slice(&fs::read(&path).expect("policy")).expect("policy JSON");
        policy["rules"][0]["rationale"] =
            json!("Updated reviewed rationale must change canonical policy evidence.");
        fs::write(
            path,
            serde_json::to_vec(&policy).expect("updated policy JSON"),
        )
        .expect("updated policy");
    }
}

impl Drop for TestRepo {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

fn feature_rule(
    feature_id: &str,
    any: serde_json::Value,
    method_count: usize,
    method_set_sha256: &str,
    positive: &str,
    negative: &str,
) -> serde_json::Value {
    json!({
        "feature_id": feature_id,
        "any": any,
        "expected": {
            "method_count": method_count,
            "method_set_sha256": method_set_sha256
        },
        "positive_examples": [positive],
        "negative_examples": [negative],
        "rationale": "Fixture rule with explicit positive and negative evidence."
    })
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut encoded = String::with_capacity(digest.len() * 2);
    for byte in digest {
        write!(&mut encoded, "{byte:02x}").expect("writing to String cannot fail");
    }
    encoded
}

fn temp_path(output: &Path) -> PathBuf {
    PathBuf::from(format!("{}{TEMP_SUFFIX}", output.display()))
}
